/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lsimedia.multiproperties.handlers;

import java.io.File;
import javax.swing.JComponent;
import lsimedia.multiproperties.Column;
import lsimedia.multiproperties.HandlerGUI;

/**
 * Empty handler configuration panel<p>
 *
 *
 * @author sbodmer
 */
public class JEmptyPropertiesHandler extends javax.swing.JPanel implements HandlerGUI {

    
    /**
     *
     */
    public JEmptyPropertiesHandler(Column column, File source) {
        initComponents();

    }

    @Override
    public JComponent getVisual() {
        return this;
    }

    @Override
    public void apply() {
        //---
    }

    @Override
    public void cancel() {
        //---

    }

        /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("No configuration");
        add(jLabel5, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables

}
