/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lsimedia.multiproperties;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author sbodmer
 */
public class JColumnValue extends javax.swing.JPanel implements ActionListener {
    String def = "";
    
    /**
     * Creates new form JColumnValue
     */
    public JColumnValue(String label, boolean disabled, String value, String def) {
        this.def = def;
        
        initComponents();
        
        CB_Column.setText(label);
        CB_Column.setSelected(!disabled);
        CB_Column.addActionListener(this);
        
        TF_Value.setText(disabled?def:value);
        TF_Value.setEditable(!disabled);
    }

    //**************************************************************************
    //*** API
    //**************************************************************************
    public boolean isDisabled() {
        return !CB_Column.isSelected();
    }
    public String getValue() {
        return TF_Value.getText();
    }
    //**************************************************************************
    //*** ActionListener
    //**************************************************************************
    @Override
    public void actionPerformed(ActionEvent e) {
        if (e.getActionCommand().equals("enable")) {
            TF_Value.setEditable(CB_Column.isSelected());
            TF_Value.setText(CB_Column.isSelected()?"":def);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CB_Column = new javax.swing.JCheckBox();
        TF_Value = new javax.swing.JTextField();

        CB_Column.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(CB_Column, org.openide.util.NbBundle.getMessage(JColumnValue.class, "JColumnValue.CB_Column.text")); // NOI18N
        CB_Column.setActionCommand(org.openide.util.NbBundle.getMessage(JColumnValue.class, "JColumnValue.CB_Column.actionCommand")); // NOI18N
        CB_Column.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        CB_Column.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        TF_Value.setEditable(false);
        TF_Value.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        TF_Value.setText(org.openide.util.NbBundle.getMessage(JColumnValue.class, "JColumnValue.TF_Value.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CB_Column, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TF_Value, javax.swing.GroupLayout.DEFAULT_SIZE, 537, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CB_Column)
                    .addComponent(TF_Value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox CB_Column;
    private javax.swing.JTextField TF_Value;
    // End of variables declaration//GEN-END:variables

    
}
