/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lsimedia.multiproperties;

import lsimedia.multiproperties.CommentRecord;
import lsimedia.multiproperties.RecordGUI;
import lsimedia.multiproperties.Column;
import java.util.ArrayList;
import javax.swing.JComponent;

/**
 *
 * @author sbodmer
 */
public class JCommentRecord extends javax.swing.JPanel implements RecordGUI {
    CommentRecord cr = null;
    
    /**
     * Creates new form JCommentRecord
     */
    public JCommentRecord(CommentRecord cr, ArrayList<Column> columns) {
        this.cr = cr;
        
        initComponents();
        
        TF_Value.setText(cr.value);
    }

    //**************************************************************************
    //*** RecordGUI
    //**************************************************************************
    @Override
    public void apply() {
        cr.value = TF_Value.getText();
    }

    public void cancel() {
        //---
    }
    
    @Override
    public JComponent getVisual() {
        return this;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        TF_Value = new javax.swing.JTextField();

        setLayout(new java.awt.BorderLayout());

        jTabbedPane1.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N

        TF_Value.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        TF_Value.setText(org.openide.util.NbBundle.getMessage(JCommentRecord.class, "JCommentRecord.TF_Value.text")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TF_Value, javax.swing.GroupLayout.DEFAULT_SIZE, 371, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TF_Value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(244, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab(org.openide.util.NbBundle.getMessage(JCommentRecord.class, "JCommentRecord.jPanel1.TabConstraints.tabTitle"), jPanel1); // NOI18N

        add(jTabbedPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TF_Value;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables

    
}
