/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lsimedia.multiproperties;

import java.awt.BorderLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.util.ArrayList;

/**
 * Open the handler to be configured
 * 
 * @author sbodmer
 */
public class JHandlerDialog extends javax.swing.JDialog implements ActionListener {

    Column column = null;
    
    HandlerGUI hgui = null;
    
    /**
     * Creates new form JWriteDialog
     */
    public JHandlerDialog(final java.awt.Frame parent, final boolean modal, final PropertiesHandler handler, final Column column, final File source) {
        super(parent, modal);
        this.column = column;
        hgui = handler.getGUI(column, source);
        
        initComponents();
    
        getContentPane().add(hgui.getVisual(), BorderLayout.CENTER);
        
        BT_Ok.addActionListener(this);
        BT_Cancel.addActionListener(this);
        
    }

    //**************************************************************************
    //*** ActionListener
    //**************************************************************************
    @Override
    public void actionPerformed(ActionEvent e) {
        if (e.getActionCommand().equals("ok")) {
            hgui.apply();
            
            setVisible(false);
            dispose();
            
        } else if (e.getActionCommand().equals("cancel")) {
            hgui.cancel();
            
            setVisible(false);
            dispose(); 
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BT_Cancel = new javax.swing.JButton();
        BT_Ok = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        BT_Cancel.setText("Cancel");
        BT_Cancel.setActionCommand("cancel");
        jPanel1.add(BT_Cancel);

        BT_Ok.setText("Ok");
        BT_Ok.setActionCommand("ok");
        jPanel1.add(BT_Ok);

        getContentPane().add(jPanel1, java.awt.BorderLayout.SOUTH);

        setBounds(0, 0, 650, 510);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        hgui.cancel();
        
        setVisible(false);
        dispose(); 
    }//GEN-LAST:event_formWindowClosing


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BT_Cancel;
    private javax.swing.JButton BT_Ok;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    
}
