/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lsimedia.multiproperties;

import java.awt.Color;
import java.awt.Component;
import javax.swing.JTable;
import javax.swing.table.TableCellRenderer;

/**
 *
 * @author sbodmer
 */
public class JRecordCellRenderer extends javax.swing.JPanel implements TableCellRenderer {

    /**
     * Creates new form JRecordCellRenderer
     */
    public JRecordCellRenderer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LB_Content = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        LB_Content.setBackground(new java.awt.Color(230, 230, 230));
        LB_Content.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(LB_Content, org.openide.util.NbBundle.getMessage(JRecordCellRenderer.class, "JRecordCellRenderer.LB_Content.text")); // NOI18N
        add(LB_Content, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LB_Content;
    // End of variables declaration//GEN-END:variables

    @Override
    public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
        LB_Content.setOpaque(column==0);
        LB_Content.setText(value.toString());
        if (isSelected) {
            LB_Content.setOpaque(false);
            setBackground(table.getSelectionBackground());
            
        } else {
            setBackground(table.getBackground());
            
        }
        return this;
    }
}
