/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lsimedia.multiproperties;

import java.awt.BorderLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;

/**
 *
 * @author sbodmer
 */
public class JWriteDialog extends javax.swing.JDialog implements ActionListener {

    Record record = null;
    
    RecordGUI rgui = null;
    
    MultiPropertiesTableModel model = null;
    
    /**
     * Creates new form JWriteDialog
     */
    public JWriteDialog(java.awt.Frame parent, boolean modal, Record record, ArrayList<Column> columns, MultiPropertiesTableModel model) {
        super(parent, modal);
        this.record = record;
        this.model = model;
        rgui = record.getGUI(columns);
        
        initComponents();
    
        getContentPane().add(rgui.getVisual(), BorderLayout.CENTER);
        
        BT_Ok.addActionListener(this);
        BT_Cancel.addActionListener(this);
        
    }

    //**************************************************************************
    //*** ActionListener
    //**************************************************************************
    @Override
    public void actionPerformed(ActionEvent e) {
        if (e.getActionCommand().equals("ok")) {
            rgui.apply();
            
            setVisible(false);
            dispose();
            
        } else if (e.getActionCommand().equals("cancel")) {
            rgui.cancel();
            
            setVisible(false);
            dispose(); 
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BT_Cancel = new javax.swing.JButton();
        BT_Ok = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        BT_Cancel.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(BT_Cancel, org.openide.util.NbBundle.getMessage(JWriteDialog.class, "JWriteDialog.BT_Cancel.text")); // NOI18N
        BT_Cancel.setActionCommand(org.openide.util.NbBundle.getMessage(JWriteDialog.class, "JWriteDialog.BT_Cancel.actionCommand")); // NOI18N
        jPanel1.add(BT_Cancel);

        BT_Ok.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(BT_Ok, org.openide.util.NbBundle.getMessage(JWriteDialog.class, "JWriteDialog.BT_Ok.text")); // NOI18N
        BT_Ok.setActionCommand(org.openide.util.NbBundle.getMessage(JWriteDialog.class, "JWriteDialog.BT_Ok.actionCommand")); // NOI18N
        jPanel1.add(BT_Ok);

        getContentPane().add(jPanel1, java.awt.BorderLayout.SOUTH);

        setBounds(0, 0, 710, 670);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BT_Cancel;
    private javax.swing.JButton BT_Ok;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    
}
